openapi: 3.1.0
info:
  version: 1.0.0
  title: Tails-FinderBD
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    A RESTful API for managing animal adverts.
    Supports user registration, authentication,
    managing adverts, filters, and enum options.
tags:
  - name: AnimalAds
    description: Operations about animal adverts
  - name: Users
    description: Operations about Users.
  - name: Filters
    description: Operations about Filters.
  - name: Auth
    description: Auth operations.
  - name: Enums
    description: Retrieve enum options for adverts.
servers:
  - url: https://tails-finderbd.onrender.com/api
    description: Production server
  - url: http://127.0.0.1:3000/api
    description: Local server
paths:
  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml


  /users/current:
    get:
      $ref: ../swagger/paths/users/current/get.yaml
  /users:
    patch:
      $ref: ../swagger/paths/users/patch.yaml


  /adverts:
    get:
      $ref: ../swagger/paths/adverts/get.yaml
    post:
      $ref: ../swagger/paths/adverts/post.yaml
  /adverts/start:
    get:
      $ref: ../swagger/paths/adverts/start/get.yaml
  /adverts/{id}:
    get:
      $ref: ../swagger/paths/adverts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/adverts/{id}/patch.yaml


  /filters:
    get:
      $ref: ../swagger/paths/filters/get.yaml
  /enums:
    get:
      $ref: ../swagger/paths/enums/get.yaml


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
